// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeleteUser struct {
	UserID string `json:"userId"`
}

type NewUser struct {
	UserID    string `json:"userId"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Dob       string `json:"dob"`
}

type User struct {
	ID        string `json:"id"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Dob       string `json:"dob"`
}
